project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Wenlong Lian"
  date: "2024/1/22"
  
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Cosmo
  pdf:
    documentclass: scrreprt

editor: visual

