project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Wenlong Lian"
  date: "2024/3/22"
  
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - readingweek.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Cosmo
  pdf:
    documentclass: scrreprt

editor: visual

