---
title: "Week5: Temperature and Policy"
format: html
editor: visual
---

# Summary

In Lecture 4, we delved into the practical applications of remote sensing in policy-making. The lecture covered policies on addressing urban heating and how RS can be used into monitoring heating and improving planning like tree planting etc.

# Application

  In exploring the application of remote sensing and analysis methods in urban heating and policy, several studies have demonstrated innovative uses and adaptations of these methodologies. A study by Clara Cruz-Ramos et al. (2021) utilized Gabor texture features and Artificial Neural Networks (ANN) for land-cover classification of urban hyperspectral images, showcasing an innovative approach to compress data features while maintaining classification accuracy, which could be pivotal for urban planning and environmental monitoring (Cruz-Ramos et al., 2021). This method's emphasis on data compression and efficient classification mirrors the analytical techniques discussed in our course, highlighting the importance of precision and efficiency in remote sensing applications.

  Similarly, Johannes H. Uhl et al. (2021) proposed a framework that integrates remote-sensing-derived data with historical maps to generate historical urban extents, offering a novel perspective on assessing urbanization and land cover change over the long term (Uhl et al., 2021). This approach not only underscores the potential of combining different data sources for enhanced urban analysis but also aligns with the course's focus on innovative data integration techniques for urban studies.


# Reflection

Reflecting on Lecture 5,  I am fascinated by the potential of remote sensing data to influence policy-making on addressing urban heating. In class, we were presented many intersting videos about how policies interact with environment and local people, and how a RS project is like which help us a lot with the final presentation.


# Reference

Cruz-Ramos, C., Garcia Salgado, B.P., Reyes-Reyes, R., Ponomaryov, V., & Sadovnychiy, S. (2021). Gabor Features Extraction and Land-Cover Classification of Urban Hyperspectral Images for Remote Sensing Applications. Remote Sensing, 13(15), 2914. [link](https://dx.doi.org/10.3390/rs13152914)

Uhl, J.H., Leyk, S., Li, Z., Duan, W., Shbita, B., Chiang, Y.-Y., & Knoblock, C.A. (2021). Combining Remote-Sensing-Derived Data and Historical Maps for Long-Term Back-Casting of Urban Extents. Remote Sensing, 13(18), 3672.[link](https://dx.doi.org/10.3390/rs13183672)